### ISSUE TITLE
Job fail in FetchedStarWarsEntity 

### ISSUE THREAD

**Issue by ismaail** [jpcaparas/laravel-horizon-demo#6]
Thanks for the demo,

The Job FetchedStarWarsEntity fails

```
ErrorException: Undefined index: name in /home/.../laravel-horizon-demo/app/Notifications/FetchedStarWarsEntity.php:56
```

Changing the attribute [$entity](https://github.com/jpcaparas/laravel-horizon-demo/blob/master/app/Notifications/FetchedStarWarsEntity.php#L21) from **private** to **public** did not fix the issue.

**Comment by jpcaparas** [comment]
Hi @ismaail,

Thanks for reaching out to me. A couple of questions:

Can you please paste the URL you've used to trigger that job?

Could you also change the method body from this:

```
    public function toMail($notifiable)
    {
        $entity = $this->getEntity();

        return (new MailMessage)
                    ->line(sprintf(
                        'Info about Star Wars entity [%1$s]', $entity['name'])
                    )
                    ->line(print_r($entity, true))
                    ->action('More details', $entity['url']);
    }
```

... to this:

```
    public function toMail($notifiable)
    {
        $entity = $this->getEntity();

        \Log::debug('Entity information', $entity);

        return (new MailMessage)
                    ->line(sprintf(
                        'Info about Star Wars entity [%1$s]', $entity['name'])
                    )
                    ->line(print_r($entity, true))
                    ->action('More details', $entity['url']);
    }
```

... and let me know what you're seeing after you run `tail -f [app-path]/storage/logs/laravel.log`

Thanks.

**Comment by jpcaparas** [comment]
Could you also do `git pull` so you have the latest commits, thanks.

**Comment by ismaail** [comment]
The url I use to create the jobs `http://[app-host]/queues/fetch-star-wars-entity?repeat=10&user_id=1`

The source of the problem is in the [$response](https://github.com/jpcaparas/laravel-horizon-demo/blob/master/app/Jobs/FetchStarWarsEntity.php#L73) 

sometime the `$response->json()` returns this array:

```php
['detail' => 'Not found']
```

**Comment by jpcaparas** [comment]
@ismaail,

That might be either swapi.co or mailtrap.io throttling your request. Have you increased the number of spawned concurrent workers on the `./config/horizon.php` file?

I'll push in a commit that throws an exception on a `404` response on both jobs. This exception should appear on the Horizon dashboard. I'll keep you posted.

Thanks,
JP

**Comment by ismaail** [comment]
I didn't change the file `config/horizon.php`.

for the emails, I used a Docker Mailcatcher.

I created a [PR](https://github.com/jpcaparas/laravel-horizon-demo/pull/8) to check the response status code.
